### ISSUE TITLE
Revamp the Community Page of the Application

### ISSUE THREAD

**Issue by N-45div** [N-45div/Resilient-Response#13]

**Comment by Mohsin-mw** [comment]
I can help with that! Do you have any figma design?

**Comment by sumanthsumu1418** [comment]
happy to take this one : )

**Comment by N-45div** [comment]
Hmm yes sure...

**Comment by sumanthsumu1418** [comment]
do yo have any figma design for the community page which i can refer..?

**Comment by sumanthsumu1418** [comment]
i have already signed in using google and when i come to community page there is a login form will username and password for community will be sent separately .. ??

**Comment by N-45div** [comment]
> do yo have any figma design for the community page which i can refer..?

No bro but you can do anything on your own according to the design of the application the main goal is that we have a collaborative community where the user has the freedom to create their profile and have amazing chat experience

**Comment by N-45div** [comment]
> i have already signed in using google and when i come to community page there is a login form will username and password for community will be sent separately .. ??

The Community that we made was using react-chat-engine API which gives the pre-made interface due to which now i think it's expired it was for 1 month...yes.

**Comment by sumanthsumu1418** [comment]
ok cool

> > i have already signed in using google and when i come to community page there is a login form will username and password for community will be sent separately .. ??
> 
> The Community that we made was using react-chat-engine API which gives the pre-made interface due to which now i think it's expired it was for 1 month...yes.
> 
> You can remove that and start with working on your idea...

ok cool

**Comment by N-45div** [comment]
How is the work going on guys @sumanthsumu1418 @Mohsin-mw

**Comment by Dhruvrode** [comment]
Hi i would like to work on this  but can you give me bried defination what exactly you want. It is my first open source contributions for HackTober

**Comment by N-45div** [comment]
@Dhruvrode community Page means buddy where the people can talk via chat and share their thoughts about the disaster that took place share pics and tell about the nearby disaster shelters...

**Comment by Akangkha** [comment]
Hey I would love to work on this. Can i use my custom details to work on this (projectId etc) and update the page design and layout ? This gonna be my first contribution to the open source community.

**Comment by N-45div** [comment]
> Hey I would love to work on this. Can i use my custom details to work on this (projectId etc) and update the page design and layout ? This gonna be my first contribution to the open source community.

Go ahead and do it..
