### ISSUE TITLE
change the sign in button on the front page

### ISSUE THREAD

**Issue by abhisar-yadav** [N-45div/Resilient-Response#25]
there should be proper spacing between sign in text on the button on the front page
[Screenshot (9)](https://github.com/N-45div/Resilient-Response/assets/112550486/bfb9a9b7-735a-4a25-9579-39845a880593)

**Comment by abhisar-yadav** [comment]
please assign me this issue

**Comment by N-45div** [comment]
@abhisar-yadav some failed checks have been do go through that once...and confirm me ..
